(defpim node (name &optional attrs attribute &rest (nodes node))
  (to-doc () (labels ((open-tag (as) (format nil "<~a~{ ~(~a~)=\"~(~a~)\"~}>" (lower name) as))
		      (close-tag () (format nil "</~a>" (lower name)))
		      (open-close-tag (as) (format nil "<~a~{ ~(~a~)=\"~(~a~)\"~}/>" (lower name) as)))
	       (if (null nodes)
		   (text  (open-close-tag attrs))
		   (vcat (text  (open-tag attrs))
			 (nest 4 (apply #'vcat (synth-all to-doc nodes)))
			 (text  (close-tag)))))))
